---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r,include=FALSE}

library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```


```{r,include=FALSE}
airbnb_data = read_csv("nyc_airbnb copy.zip") %>% 
  clean_names() %>% 
  rename(boro = neighbourhood_group) %>% 
  mutate(rating = review_scores_location/2) %>% 
  filter(boro == "Manhattan",
         room_type =="Entire home/apt",
         price>100 & price<400)
```
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r}
airbnb_data %>% 
  mutate(hover_text= str_c("Price: $", price, "\nRating", rating)) %>% 
  plot_ly(x= ~longitude, y= ~latitude, type="scatter", mode="marker",
          alpha=0.5, color=~price, text= ~hover_text)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B
```{r}
airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```

### Chart C
```{r}
scatter_ggplot= airbnb_data %>% 
  ggplot(aes(longitude, y= latitude, color = price)) + 
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic() 
  

ggplotly(scatter_ggplot)
```

